### Create a new person
POST http://localhost:9000/people
Content-Type: application/json

{
  "name": "Rodrigo Rangel",
  "age": 38,
  "student": false
}

### Get all people
GET http://localhost:9000/people
Accept: application/json

### Get a specific person by ID
GET http://localhost:9000/people/1
Accept: application/json

### Update a person
PUT http://localhost:9000/people/1
Content-Type: application/json

{
  "name": "John Smith",
  "age": 31,
  "student": true
}

### Delete a person
DELETE http://localhost:9000/people/1
Accept: application/json
